version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  starrocks:
    image: registry.starrocks.io/starrocks/allin1-ubuntu
    ports:
      - "9030:9030"
    networks:
      - mynetwork
    container_name: starrocks_container

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'your_mysql_root_password'
    networks:
      - mynetwork
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
