name: Deploy to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3 # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v3 # Updated to the latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      run: twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}
